--Initial user rights.

BEGIN TRANSACTION;

REVOKE ALL ON SCHEMA prada FROM PUBLIC;
REVOKE ALL ON ALL TABLES IN SCHEMA prada FROM PUBLIC;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA prada FROM PUBLIC;
REVOKE ALL ON SCHEMA prada FROM "tng_prada_system";
REVOKE ALL ON ALL TABLES IN SCHEMA prada FROM "tng_prada_system";
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA prada FROM "tng_prada_system";


/**tng_prada_system**/

REVOKE ALL ON SCHEMA prada FROM "tng_prada_system";
GRANT ALL ON SCHEMA prada TO "tng_prada_system"; -- WITH GRANT OPTION;

REVOKE ALL ON ALL TABLES IN SCHEMA prada FROM "tng_prada_system";
ALTER DEFAULT PRIVILEGES IN SCHEMA prada
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLES TO "tng_prada_system";
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON ALL TABLES IN SCHEMA prada TO "tng_prada_system";

REVOKE ALL ON ALL FUNCTIONS IN SCHEMA prada FROM "tng_prada_system";
ALTER DEFAULT PRIVILEGES IN SCHEMA prada
GRANT EXECUTE ON FUNCTIONS TO "tng_prada_system";
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA prada TO "tng_prada_system";

REVOKE ALL ON ALL SEQUENCES IN SCHEMA prada FROM "tng_prada_system";
ALTER DEFAULT PRIVILEGES IN SCHEMA prada
GRANT SELECT, UPDATE, USAGE ON SEQUENCES TO "tng_prada_system";
GRANT SELECT, UPDATE, USAGE ON ALL SEQUENCES IN SCHEMA prada TO "tng_prada_system";


REVOKE ALL ON SCHEMA cpic FROM "tng_prada_system";
GRANT ALL ON SCHEMA cpic TO "tng_prada_system"; -- WITH GRANT OPTION;

REVOKE ALL ON ALL TABLES IN SCHEMA cpic FROM "tng_prada_system";
ALTER DEFAULT PRIVILEGES IN SCHEMA cpic
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLES TO "tng_prada_system";
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON ALL TABLES IN SCHEMA cpic TO "tng_prada_system";

REVOKE ALL ON ALL FUNCTIONS IN SCHEMA cpic FROM "tng_prada_system";
ALTER DEFAULT PRIVILEGES IN SCHEMA cpic
GRANT EXECUTE ON FUNCTIONS TO "tng_prada_system";
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA cpic TO "tng_prada_system";

REVOKE ALL ON ALL SEQUENCES IN SCHEMA cpic FROM "tng_prada_system";
ALTER DEFAULT PRIVILEGES IN SCHEMA cpic
GRANT SELECT, UPDATE, USAGE ON SEQUENCES TO "tng_prada_system";
GRANT SELECT, UPDATE, USAGE ON ALL SEQUENCES IN SCHEMA cpic TO "tng_prada_system";


COMMIT;
